Job launching after 0.38 seconds in submission.
Running python job.
Changed into dir /Users/weisser/Dropbox (MIT)/MIT/Research/MLTools/Dalitz_simplified/spearmint
Importing classifier_eval_wrapper.py
Running classifier_eval_wrapper.main()
/usr/local/lib/python2.7/site-packages/sklearn/svm/base.py:176: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  (self.gamma == 'auto')):
/usr/local/lib/python2.7/site-packages/sklearn/svm/base.py:179: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.gamma == 'auto':
Traceback (most recent call last):
  File "/Users/weisser/Documents/Spearmint-master/spearmint/launcher.py", line 243, in launch
    result = python_launcher(job)
  File "/Users/weisser/Documents/Spearmint-master/spearmint/launcher.py", line 327, in python_launcher
    result = module.main(job['id'], params)
  File "/Users/weisser/Dropbox (MIT)/MIT/Research/MLTools/Dalitz_simplified/spearmint/classifier_eval_wrapper.py", line 11, in main
    return classifier_eval_simplified.classifier_eval(params['aC'], params['agamma'],2)
  File "../classifier_eval_simplified.py", line 219, in classifier_eval
    scores = cross_validation.cross_val_score(clf,X,y,cv=acv,scoring=p_value_scoring_object.p_value_scoring_object)
  File "/usr/local/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1433, in cross_val_score
    for train, test in cv)
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python2.7/site-packages/sklearn/svm/base.py", line 193, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python2.7/site-packages/sklearn/svm/base.py", line 251, in _dense_fit
    max_iter=self.max_iter, random_seed=random_seed)
KeyboardInterrupt
Problem executing the function
Job failed in 2919.41 seconds.

This script can be used to get the p value for classifiers. It takes input files with column vectors corresponding to features and lables. 
Then there are two different routes one can go down. When mode has a value of 1, then a grid search will be performed on 
one set of input files. If it is 2, then the hyperparemeter search is performed by spearmint. When the mode is turned off (0), 
then the p value is computed for multiple sets of input files and the p value distribution is plotted.  

Anything printed here will end up in the output directory for job #7
{u'aC': array([ 991.8644537]), u'agamma': array([ 100.])}
Operating of files :/Users/weisser/MIT_Dropbox/MIT/Research/MLTools/Dalitz/dpmodel/data/data.0.0.txt   /Users/weisser/MIT_Dropbox/MIT/Research/MLTools/Dalitz/dpmodel/data/data.200.1.txt
[[ 0.223941  0.390803]
 [ 0.701962  0.161561]
 [ 0.12984   0.164384]
 ..., 
 [ 0.303883  0.476474]
 [ 0.164612  0.455126]
 [ 0.19098   0.291134]]
[ 0.  0.  1. ...,  1.  1.  1.]
(<type 'exceptions.KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x114568908>)
Traceback (most recent call last):
  File "/Users/weisser/Documents/Spearmint-master/spearmint/launcher.py", line 415, in <module>
    main()
  File "/Users/weisser/Documents/Spearmint-master/spearmint/launcher.py", line 219, in main
    launch(options.db_address, options.experiment_name, options.job_id)
  File "/Users/weisser/Documents/Spearmint-master/spearmint/launcher.py", line 293, in launch
    db.save(job, experiment_name, 'jobs', {'id' : job_id})
  File "/Users/weisser/Documents/Spearmint-master/spearmint/utils/database/mongodb.py", line 218, in save
    dbdocs       = list(dbcollection.find(field_filters))
  File "/usr/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1012, in _refresh
    self.__read_concern))
  File "/usr/local/lib/python2.7/site-packages/pymongo/cursor.py", line 850, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 781, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 142, in select_server
    address))
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 118, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
